### ISSUE TITLE
Anyone gotten GPU passthrough to work with a 7900XTX?

### ISSUE THREAD

**Issue by BaconIsAVeg** [mike11207/single-gpu-passthrough-amd-gpu#14]
I have a Gigabyte Radeon RX 7900 XTX Gaming OC 24G and it doesn't appear on the techpowerup site.  Also even the most recent amdvbflash that I've found (for Linux) doesn't recognize it, it seems like the Linux releases are far behind the windows release.

I've followed several guides with no luck, I'm starting to think it's card related.

**Comment by catsgomoo** [comment]
From what I know RDNA3 does not work well (or at all) with GPU Passthrough
