### ISSUE TITLE
Black screen.

### ISSUE THREAD

**Issue by Zeddesnetos** [mike11207/single-gpu-passthrough-amd-gpu#2]
OS: Arch Linux, Linux Zen
GPU: AMD Radeon 5600XT

I followed this guide but all i got was a black screen in the end. (My displays are showing "no signal") the same it was with the other tutorial: https://github.com/joeknock90/Single-GPU-Passthrough

**Comment by rolexlinux** [comment]
can u send the output of `/var/log/libvirt/qemu/win10.log`

**Comment by rolexlinux** [comment]
Try adding `disable_idle_d3=1` into your boot parameters.
